name: Build AminTranslate Native Pro APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Recreate native Android project
        shell: bash
        run: |
          cat > project.b64 <<'EOF_PROJECT'
          UEsDBAoAAAAAACItPV0AAAAAAAAAAAAAAAAXABwAQW1pblRyYW5zbGF0ZU5hdGl2ZVByby9VVAkA
          A29Pu2pvT7tqdXgLAAEEAAAAAATpAwAAUEsDBBQAAAAIACItPV0LvDKgzgAAAIABAAAmABwAQW1p
          blRyYW5zbGF0ZU5hdGl2ZVByby9zZXR0aW5ncy5ncmFkbGVVVAkAA29Pu2pvT7tqdXgLAAEEAAAA
          AATpAwAArY/BagIxEIbveYrcopf1LvQgotBS3bB6X4bNkMZmZ0IyKxTx3d1KWcSDp/7Hb/4Z5ktx
          8IF2QOCxRxJ9UXpMxsQlCOeA5Q/9xjP7iLP5BHo4I63HvQzxAfsMLqK937acZRpe1VUphwnJIXU/
          DRaOgwR+/cGOHVYFZdY8w+3q/bOt961t6o/N+tg2G1sf5v+hcMf6oocctfkSSWW5WJyCJOi+q8Bm
          VJmEMrPYzCfspCLoUb9ps+oDHTNQiSC4BwlnHCtGBeri4FCbJaRk1A1QSwMECgAAAAAAIi09XQAA
          AAAAAAAAAAAAABsAHABBbWluVHJhbnNsYXRlTmF0aXZlUHJvL2FwcC9VVAkAA29Pu2pvT7tqdXgL
          AAEEAAAAAATpAwAAUEsDBAoAAAAAABQtPV0AAAAAAAAAAAAAAAAfABwAQW1pblRyYW5zbGF0ZU5h
          dGl2ZVByby9hcHAvc3JjL1VUCQADWE+7alhPu2p1eAsAAQQAAAAABOkDAABQSwMECgAAAAAAIi09
          XQAAAAAAAAAAAAAAACQAHABBbWluVHJhbnNsYXRlTmF0aXZlUHJvL2FwcC9zcmMvbWFpbi9VVAkA
          A29Pu2pvT7tqdXgLAAEEAAAAAATpAwAAUEsDBAoAAAAAABQtPV0AAAAAAAAAAAAAAAAoABwAQW1p
          blRyYW5zbGF0ZU5hdGl2ZVByby9hcHAvc3JjL21haW4vcmVzL1VUCQADWE+7alhPu2p1eAsAAQQA
          AAAABOkDAABQSwMECgAAAAAAIi09XQAAAAAAAAAAAAAAAC8AHABBbWluVHJhbnNsYXRlTmF0aXZl
          UHJvL2FwcC9zcmMvbWFpbi9yZXMvdmFsdWVzL1VUCQADb0+7am9Pu2p1eAsAAQQAAAAABOkDAABQ
          SwMEFAAAAAgAIi09XcPI6+/kAAAA2gEAADkAHABBbWluVHJhbnNsYXRlTmF0aXZlUHJvL2FwcC9z
          cmMvbWFpbi9yZXMvdmFsdWVzL3RoZW1lcy54bWxVVAkAA29Pu2pvT7tqdXgLAAEEAAAAAATpAwAA
          lZHBbsIwDIbvPEUUzmvpadOUFjEkToMdxgtYjVssJc6UuGW8/bIWpO0yMZ/9+bP9m/Wnd2rEmChw
          ratipRVyGyxxX+tBuocnvW4WJmIKQ2wxNQuVyyS5OFQMHmt9PKHHYuOJjxE4ORA8gNCIWn1ARJZa
          A9sYyD5PWDkD+9wXCVxxCJtWsv4Fop7HTwoS9FfDDe8Cyw48uYtuUlaZ8rvpb+ZMbMP5lfqTvAvI
          kCZNBy7hPXi6MdvgQgaXq8eqqnb3oAwj9XC97P/4vPj8mn2w+JZTcpAvlzj8Wt2U01tzSuWPmL4A
